package org.nmjava.chatapp.commons.enums;

public enum RequestType {
    AUTHENTICATION,
    CREATE_ACCOUNT,
    FORGOT_PASSWORD,
    GET_LIST_CONSERVATION,
    GET_LIST_MESSAGE_CONSERVATION,
    GET_LIST_FRIEND,
    GET_LIST_FRIEND_ONLINE,
    GET_LIST_REQUEST_FRIEND,
    ACCEPT_REQUEST_FRIEND,
    SEND_MESSAGE,
    DELETE_MESSAGE,
    SEARCH_MESSAGE_USER,
    SEARCH_MESSAGE_ALL,
    CREATE_GROUP_CHAT,
    RENAME_GROUP_CHAT,
    ADD_MEMBER_GROUP_CHAT,
    GIVE_ADMIN_USER_GROUP_CHAT,
    REMOVE_USER_GROUP_CHAT,
}
